version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo installing npm packages
      - npm install
  build:
    commands:
      - echo build started
      - npm run build

  post_build:
    commands:
      - echo post_build started on 'date'
      # - aws s3 sync public/ rufiltestbucket --exclude "*.map" --acl public-read --delete
      - aws s3 sync public/ s3://rufiltestbucket --delete --acl public-read