version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo installing npm packages
      - npm install

  build:
    commands:
      - echo build production started
      - npm run build

  post_build:
    commands:
      - echo post_build started on `date`
      - aws s3 sync public/ s3://rufiltestbucket --delete --acl public-read
      - aws cloudfront create-invalidation --distribution-id E2ZL20JM3QE32H --paths "/*";
  # cache:
  #   paths:
  #     - 'node_modules/**/*'
