version: 0.1
phases:    
    install:
      runtime-versions:
        nodejs: 10
        commands:
            - echo installing npm packages
            - touch .npmignore            
            - npm install -g gatsby    
    pre_build:        
        commands:            
            - npm install   
    build:        
        commands:
            - echo build started          
            - npm run build
    post_build:        
        commands:
            - echo post_build started on 'date'
            - aws s3 sync public/ $BUCKET --exclude "*.map" --acl public-read --delete
artifacts:    
    base-directory: public    
    files:        
        - '**/*'
    discard-paths: yes